### ISSUE TITLE
EventsController exceeds int value.

### ISSUE THREAD

**Issue by rafiqueud** [maxio-com/ab-java-sdk#127]
Hello guys, while using your SDK when you try to list events I got an error:

`JsonMappingException: Numeric value (4xxxxxxxxx1) out of rang of int (-21474883648 - 21474883648 `

**Comment by michalpierog** [comment]
@rafiqueud Hi, this bug should be fixed in version 2.0.0

**Comment by michalpierog** [comment]
@rafiqueud can you confirm the new version is working for you?
